### ISSUE TITLE
Drop clock routine usage from wait_for function (and make systimer mandatory)

### ISSUE THREAD

**Issue by forGGe** [forGGe/theCore#247]
Systimer implementation: #246 

Inside theCore, timers are used mainly for delay control. Two interfaces are present: [`platform/common/execution.hpp`](https://github.com/forGGe/theCore/blob/develop/platform/common/export/common/execution.hpp#L27) and bunch of `lib/thread`-related routines, one per each OS (see [FreeRTOS example](https://github.com/forGGe/theCore/blob/develop/lib/thread/freertos/export/ecl/thread/utils.hpp#L29))

Same interface is exposed to the user and collisions can occur in certain cases when both user and theCore will try to manage timers directly or indirectly (via delay-like API, for example). OS presence is also affects timers allocation and dependent interfaces.

To address that conflict, **the user must define in built time whether particular timer is given to theCore for full control, or not**. Since timers are platform-related, the build option must be platform-dependent. For example, the variable with name `CONFIG_USE_SYSTMR_SYSTICK` can be implemented, so that setting it to `1` on stm32 platform will force theCore to use SysTick as main timer for its own needs.

The list of notable cases below assumes that above statement is always true, i.e. if user decided to give full control over the timer to theCore, then it will not try to get control back in runtime.

| Description                                                                                              | Timer ownership | OS presence | Build parameters                                                                           | lib/thread                                                     | common/execution                                                                   | Notes                                                                          |
|----------------------------------------------------------------------------------------------------------|-----------------|-------------|--------------------------------------------------------------------------------------------|----------------------------------------------------------------|------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| User want to use theCore in transparent manner and control timers by himself. No OS present. Basic case. | User            | No OS       | `CONFIG_USE_SYSTMR*` variables are set to `0` (depends on platform) or not defined at all. | Non-OS stubs should call `common/execution` routines.          | Calls `spin_wait()` (and possibly other API) from `platform/execution`             | Requires at least `spin_wait()` present in the `platform/execution` API        |
| User has enabled FreeRTOS (or any OS that uses timers).                                                  | OS              | FreeRTOS    | `CONFIG_USE_OS` set to desired OS.                                                         | OS-aware wrappers should call OS-related delay management API. | Calls `spin_wait()` (and possibly other API) from `platform/execution`             | Requires at least `spin_wait()` present in the `platform/execution` API        |
| User gave timer control to theCore.                                                                      | theCore         | No OS       | `CONFIG_USE_SYSTMR*` set to 1.                                                             | Non-OS stubs should call `common/execution` routines.          | Calls `systmr` set of functions (and possibly other API) from `platform/execution` | Requires `systmr`API present in the `platform/execution`                       |
| User gave timer control to theCore **and** enabled OS.                                                   | **undefined**   | FreeRTOS    | `CONFIG_USE_SYSTMR*` set to 1 and `CONFIG_USE_OS` set to desired OS.                       | **error case**                                                 | **error case**                                                                     | **Such case is prohibited, since it raises collisions between OS and theCore** |

Couple of footnotes:
 - WFI/WFE interface should not be used if OS present.
 - Delay routines are not forced to precisely count the delay. Only lower timeout boundary can be satisfied. I.e. given 1ms as an argument to `sleep_for` can result in delay >= 1 ms, but not less.
 - Predicate checks in delay routines with conditions can be executed with some time quant in case if OS is present, or do WFI/WFE otherwise and supported.

**Comment by vadimol** [comment]
1) Each platform provides `platform_spin_wait()` and (optionally) `SYSTMR` implementation.
2) Common-execution provides `spin_wait() `and `wait_for()`, The `wait_for()` uses ` spin_wait()` in case `SYSTMR` is not available.
3) The thread-lib provides `sleep_for()` that uses `wait_for()` from common-execution or OS specific interface if available.
@forGGe , what do you think?

**Comment by forGGe** [comment]
@vadimol looks good but have one question. What is relationship between `spin_wait()` and `platform_spin_wait()` ? If `spin_wait()` will call `platform_spin_wait()` no matter what, then it is reasonable to keep `spin_wait()` only in platform headers (they are exposed via `common/execution.hpp` in any case)

**Comment by forGGe** [comment]
@vadimol thanks! implementation completed, closing this issue.
