### ISSUE TITLE
The Core CS43L22 audio example does not work in release mode

### ISSUE THREAD

**Issue by rasendubi** [forGGe/theCore#249]
I have built the example following the instructions but added `-DCMAKE_BUILD_TYPE=Release`. The result is no sound.

I can't tell the USART output, as I don't have it connected. But here is a screenshot of the I2C session. It is much shorter than in debug mode, the initialization sequence is truncated.

![2017-05-05-025633_914x162_scrot](https://cloud.githubusercontent.com/assets/1366419/25729515/7b70faac-313e-11e7-8857-ce4d5fc7d659.png)

**Comment by rasendubi** [comment]
(Debug build works fine.)

**Comment by forGGe** [comment]
Bug confirmed

**Comment by forGGe** [comment]
Fixed in #250
